#!/bin/sh

. "$(dirname "0")/../external/shflags/shflags"
. "$(dirname "0")/../tools/msg.sh"
. "$(dirname "0")/../tools/os.sh"
. "$(dirname "0")/../tools/pkg.sh"


sudo rm -rfv /var/lib/postgres/data/*

pkg_remove postgresql
pkg_remove postgresql-libs

msg_info "removing postgres cluster"
sudo rm -rfv /var/lib/postgres/data/*
msg_ok "postgres cluster removed"
